substitutions:
  _ML_API_IMAGE: europe-west1-docker.pkg.dev/nl-sql-peft-lab-ivan-0429/nl-to-sql-peft-lab/ml-api:latest
  _RUNTIME_IMAGE: europe-west1-docker.pkg.dev/nl-sql-peft-lab-ivan-0429/nl-to-sql-peft-lab/runtime:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - Dockerfile.ml-api
      - --build-arg
      - RUNTIME_IMAGE=${_RUNTIME_IMAGE}
      - -t
      - ${_ML_API_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_ML_API_IMAGE}

images:
  - ${_ML_API_IMAGE}

timeout: 1200s
