substitutions:
  _APP_IMAGE: europe-west1-docker.pkg.dev/nl-sql-peft-lab-ivan-0429/nl-to-sql-peft-lab/app:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - Dockerfile.app
      - -t
      - ${_APP_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_APP_IMAGE}

images:
  - ${_APP_IMAGE}

timeout: 1200s
