workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: europe-west1-docker.pkg.dev/nl-sql-peft-lab-ivan-0429/nl-to-sql-peft-lab/train:latest
      command: [python3, scripts/run_causal_peft_pipeline.py]
      env:
        - name: TRAIN_CONFIG
          value: configs/qwen2_5_wikisql_qlora_early_stopping.yaml
        - name: BENCHMARK_CONFIG
          value: configs/qwen2_5_wikisql_qlora_early_stopping_benchmark.yaml
        - name: GCS_OUTPUT_URI
          value: gs://nl-sql-peft-lab-ivan-0429-training/runs/v0.2/qwen2-5-wikisql-qlora-early-stopping
        - name: TRAINING_SERVICE
          value: Vertex AI Custom Job
        - name: TRAINING_REGION
          value: europe-west4
        - name: MACHINE_TYPE
          value: n1-standard-8
        - name: ACCELERATOR_TYPE
          value: NVIDIA_TESLA_T4
        - name: ACCELERATOR_COUNT
          value: "1"
    diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
